apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: recycle-me-app-cluster
  region: us-east-1

vpc:
  id: vpc-00de74a7be6ed35f4  
  subnets:
    private:
      us-east-1a:
        id: subnet-0bb85f00724b2bffb
      us-east-1b:
        id: subnet-0c1597298ef06cd97
    public:
      us-east-1a:
        id: subnet-090f7c82441b1dcf9
      us-east-1b:
        id: subnet-0e8a2be12452a4ee1

nodeGroups:
  - name: ng-flask-app
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
